---
- hosts: all
  vars:
    iface: '{{ ansible_default_ipv4.interface }}'
    data_dir: /mnt/data
  remote_user: ec2-user
  sudo: yes
# todo - ensure epel repo is enabled
  tasks:
  - name: Ensure packages are up to date
    yum: name=* state=latest
  - name: Ensure mongodb is installed and latest version
    yum: pkg={{ item }} state=latest
    with_items:
      - mongodb
      - mongodb-server
  - name: Create the hosts file for all machines
    template: src=templates/hosts.j2 dest=/etc/hosts
  - name: Create the data directory 
    file: path={{ data_dir }} owner=mongodb group=root state=directory mode=0755

#    notify:
#    - restart apache
#  - name: ensure apache is running
#    service: name=httpd state=started
#  handlers:
#    - name: restart apache
#      service: name=httpd state=restarted
